### PR TITLE
Use maven dist management from Apache parent pom

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by smoyer64** [comment]
That ``distributionManagement`` section is tied to the signing keys on our Jenkins server and the PennState account at OSS Sonatype.  Is it safe to assume that snapshot and release versions will be distributed in the same way using the Apache Jenkins server?

**Comment by bdemers** [comment]
Yes, though the actual release process will likely change somewhat (due to the [Apache process](https://www.apache.org/dev/release-publishing.html)) I'm not sure what the directory projects currently do.

**Comment by seelmann** [comment]
As you already switched to the Directory parent POM the distmgmt points to https://repository.apache.org, so should be fine.

Each subproject has a "Developer guide" which should document the release process. Not all are yet up-to-date after SVN to Git migration. Probably the best is the Fortress one: https://directory.apache.org/fortress/developer-guide.html

**Comment by smoyer64** [comment]
Perfect ... I think we've been releasing frequently in comparison with the other Apache Directory projects but we'll definitely have to document what we've been doing.  Thanks for the notes above!

**Comment by elecharny** [comment]
Note that we have to review all of those documents, as the Apache release policy has tighten up the rules recently...

**Comment by smoyer64** [comment]
Yes ... I didn't mean to imply that what we document not conform to the Apache release rules (I read through that thread on the dev list).

**Pull request merged**
