### PR TITLE
Add OWASP suppression to ignore false positives

### PR DESCRIPTION
**Pull request by bdemers**
Also moved the jetty-bom import to root pom, as scim-coverage wasn't getting the updated versions

### CODE REVIEW

**Comment by smoyer64** [comment]
Restfuse is no longer supported and I'll be moving compliance tests to a different framework at some point.  In any case, restfuse should have been test scoped in the parent POM which would have resulted in OWASP ignoring it (since it's not a run-time dependency).  I'll test that this works tomorrow morning and push an alternate change.

In general I'm not a fan of using the suppression files except for dependencies that are truely false positives.  In theory, these should be submitted to the OWASP maintainers so that it's included in their global suppression file.  E.g - The OAuth2 library we use also supports OpenId Connect.  One of the OWASP rules marks anything with the word openid in it as vulnerable to the unrepairable OpenId problem.  But OpenId Connect is flagged even though it's completely different.

**Comment by bdemers** [comment]
I share your concerns. The exclude file currently only contains GAVs of the current project, so it is pretty save to include them, (they are getting picked up as an old HTTP Server component).

Sounds like your proposed Restfuse change will fix the other half though!

**Comment by smoyer64** [comment]
Switching restfuse to ``<scope>test</scope>`` causes the compliance module to fail.  Since it's supposed to be a test tool (as an executable JAR), the test classes are located in ``src/main/java`` rather than ``src/test/java``.  I'll do some work on this next week and, at a minimum, will remove the restfuse dependency and (temporarily) remove the compliance module from the parent POM.

**Comment by bdemers** [comment]
@smoyer64 you mentioned OAuth2/OIDC support, can you point me to how/where it is configured (if it is an _easy_ answer)?  I can start another thread, but I figured I'd ask here first because you referenced it above

**Comment by smoyer64** [comment]
We have custom PSU clients in our repository that work with our OAuth2 server - we currently don't use OIDC.  The server implementations allow the provider to dictate the security constraints and those are driven by our Apache Directory Fortress servers (ANSI RBAC) with a custom JASPI layer.  I don't think there's anything proprietary in there so it might be something we're willing to move to an OSS project but I don't think we want to require those in a server implementation.  Maybe a pluggable security layer that can be added?

And we should probably start another thread since I expect this PR will be closed next week with or without some work on the compliance modules.  Authentication and Authorization is going to be a much longer discussion.

@ussmith @chrisharm @pike1212

**Comment by smoyer64** [comment]
Looking through what I was trying to accomplish in the compliance modules, I think that in the long-term getting rid of restfuse (and therefore the Jetty dependency) and moving to JUnit 5 is probably a wise move. In any case, it wasn't really functional enough to be worth keeping. I'm merging this PR to get the build running again, then will make changes to the compliance module.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by smoyer64** [comment]
The scim-server-common module's vulnerabilities are suppressed by this change ... there's quite a list of vulnerabilities that show up and it would be nice to get a clean build on that module.  I'll remove the Jetty override in a future commit.

**Pull request merged**
