### PR TITLE
Add Jacoco Maven plugin to record test coverage

### PR DESCRIPTION
**Pull request by bdemers**
Each module will output a coverage file, but only a total project report is generated
at {root}/scim-coverage/target/site/jacoco-aggregate/index.html

NOTE: this is layered on PR #3, diff to review: a48f7db

### CODE REVIEW

**Comment by smoyer64** [comment]
I'm a fan ... if you rebase to develop I'll merge this right now.

**Comment by bdemers** [comment]
@smoyer64 my pref is to get #3 in first, as this commit adds another module (with the new GAV).  If that one is blocked however let me know

**Comment by smoyer64** [comment]
I've merged #3 - pull those changes into this PR and we'll get it merged too.  Thanks for all the help ... I'm pretty excited about the better marketing story this project has as part of the ASF and it would be great to grow a larger community of developers who can push us towards being specification compliant!

**Comment by bdemers** [comment]
@smoyer64 this should merge clean now

**Comment by smoyer64** [comment]
There are still a bunch of references to ``<version>2.0-SNAPSHOT</version>`` in the two changed files.  I was expecting a rebase to fix them but now I notice that they're mostly new "code" in this PR.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by bdemers** [comment]
@smoyer64 sorry about that, I'll clear my local repo fix and verify
(i'm trying to setup a PR CI job to catch this type of thing)

**Comment by bdemers** [comment]
@smoyer64 got it, I'm juggling a bunch of small branches 😄

**Comment by smoyer64** [comment]
NP ... I've been there too

**Pull request merged**
