### PR TITLE
IDEA: Replace restfuse with Rest Assured based tests

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by bdemers** [comment]
I ported the existing tests,  I'm going to start with CRUD tests for the User endpoints next, but I'd like feed back first (if possible)

**Comment by smoyer64** [comment]
The plan is to eventually replace the Restfuse tests with JUnit 5 / upREST tests ... upREST will be moving to the junit-pioneer project but it needs some work to comply with the release version of JUnit 5.

The compliance tests are meant to be a TCK and, using the junit-platform-launcher should be an executable fat JAR (though I'm not sure which type).  The reason RestFuse was not test scoped is that the TCK should be an executable.  So even though it's using a testing framework, it's actually an application.

**Comment by bdemers** [comment]
I can see how an self contained jar would be useful, but it should be an attached artifact if anything.  I’d rather just pull the tests as a dep and run them with surefire/failsafe.

(Was messing with doing that today against the examples)

**Comment by bdemers** [comment]
@smoyer64 upREST looks like a cool project. I have some concerns though: no releases, hasn't been touched in a year, very light doc, needs to be updated to use latest JUnit 5, moved to a new home (junit-pioneer).

I'm not trying to be critical of the upREST.  I'm just not sure we should tie the success of this project (and lack of IT) to an that project.

I can switch to JUnit 5, and rename the module to `scim-compliance-server-beta` or something.  That way it gives us the opportunity to make progress on SCIMple testing, and allows us to throw it away if something better matures (i.e. upREST).

Thoughts?

**Comment by bdemers** [comment]
Added example of running project examples against these ITs

I'm not super happy with how Arquillian needs to be configured, i'm sure there is some JUnit magic that could be configured here 🤔

**Comment by smoyer64** [comment]
There has been little progress within the SCIM community towards creating an official TCK and I'd hoped we could eventually provide that.  I think that for those using SCIM with the Java programming language, running via the ``maven-failsafe-plugin`` isn't an issue.  My thought behind making this a Java application (preferably some sort of shaded/uber JAR) was that it would be easier for the rest of the SCIM community to run (i.e. those using other languages).

I know upREST is behind ... there's more on my laptop than what's on Github but I'm trying to figure out a good way to do authentication at the moment.  There are some things that I like about the declarative nature of Restfuse that I was trying to carry forward.  What you've done with RestAssured looks pretty good (I'm not a fan of using it with Groovy) so perhaps it does make sense going forward.  We tend to use AssertJ rather than Hamcrest ... I don't remember whether there's already a dependency for that.

I hadn't spent any real time thinking about the client compliance suite but why are you using Arquillion for the server compliance testing?  It could almost be a Postman configuration and really just needs a REST client that calls the server implementation.  If you're simply using Arquillion for CDI there's weld-junit5 which provides a nice CDI integration.  If you're starting up a server (the in-memory server?) to run tests against, I'd argue that that should be something run as a separate step.

To convert to JUnit 5, there's a nice utility that our friend (and JavaOne co-conspirator) @boyarsky wrote that will do a lot of the conversion - https://github.com/boyarsky/convert-junit4-to-junit5.  Be aware that there is no concept for Runners in JUnit 5 so using the Arquillion runner won't work.

I see there are a bunch of files outside the compliance modules included in this PR ... Can those be separated into other PRs?  Changing server-common has the potential to introduce breaking changes to the providers we've got in production.  We've been using the lack of failures in PSU implementations as part of the validation for those PRs.  Some day there should be enough tests in SCIMple itself to identify breaking changes!

**Comment by bdemers** [comment]
There are a few points/questions here :)

* Hamcrest comes in with JUnit

* Starting a server under test (in this case Tomee) should be managed by the test/test infrastructure.  (not out of band i.e. Maven pre-integration-test).  This allows for tests to run via an IDE as well as via the command line, which makes for a great developer experience.
The `scim-example-memory` module is a war, so it _should_ be tested that way (for ITs anyway)

* Re: JUnit 5 + Arquillia - ugg... I guess there are other options for Arquillia, using a rule maybe 🤔, or just stay with JUnit 4 until that tooling around 5 matures ?

* Change outside of the test might have shown up before I rebased.  If you see something specific now let me know.  There _should_ only be changes related to the new ITs and running them.

* Adding tests to detect breaking changes 100% the goal of this PR ;) I just wanted to get feed back before I added other ITs.


I think maybe we should reduce scope of the compliance module:

* Rename it ? - I love the generic compliance test use case, but it might be easier to start with something project specific and work out from there? (focusing on this project's needs first), mark the classes as `internal` so we are not bound to keep it backward compatible (allowing us to rev fast on the tests)
* Sort out the testing frameworks with something off the shelf, (including something that can launch and run the examples, assuming we will add more examples)
* Maybe even launch the example apps from maven in a pre-IT phase (though I loathe suggesting that)

**Comment by smoyer64** [comment]
I should have also noted that now that JUnit 5 includes ``@ParameterizedTest`` we can do some a version of the tests I started designing upREST for - ``ServiceProviderConfig``, ``ResourceType`` and ``Schemas`` should error the same way for mutating HTTP verbs.

So Arquillian is being used to test the tests against the in-memory server?  That sounds reasonable except that the in-memory server has a long way to go to be SCIM compliant.  I was actually going to write the compliance test modules using first-principles from the specification.

Since you're not using Arquillian to actually build the test environment, one way to spin up the "server-under-test" is to start the WAR in a docker container during the ``pre-integration`` phase and shut it down in ``post-integration``.  As you noted, Arquillian is a pain to set up and since you're not shrinkwrapping small sections of the server, why not just spin it up in Docker?

Hamcrest doesn't come in with JUnit 5 ... and of course AssertJ works with JUnit 4.  I don't mind the scope of the current compliance modules but I do recognize there's a long way to go with them.  I think this discussion is more important since it's going to set the tone for how we can all collaborate on them (which frameworks to use, how to test the tests etc).  When you describe a "great developer experience", you're again speaking for those using Java/Maven - and even then, when Arquillian breaks it can be pretty incomprehensible.  Let's start with what you have and try to reach the original goal of the compliance module?  Converting working tests in ``src/test/java`` into a stand-alone TCK should be as easy as moving them to ``src/main/java`` and adding a "shim" to start the JUnit 5 launcher.  Alternately, we could configure the ``maven-jar-plugin`` to also package the test classes which would leave the tests where the ``maven-failsafe-plugin`` is expecting them.  Maybe that's the best of both worlds.

So the final question is how do we solve the chicken-and-egg problem - in order to have a verified TCK to run against a SCIM server, we need a fully compliant SCIM server as well as one that can serve all the potential errors we'd expect to see.  Maybe the in-memory server example will work ... it seems like the best place to start for now.

**Comment by bdemers** [comment]
Similar Rest Assured based tests have been added

**Pull request closed without merging**
