### PR TITLE
Add in memory example - Port PennState in memory server example to new Apache structure

### PR DESCRIPTION
**Pull request by bdemers**
Added README, but basically just run `mvn tomee:run`

### CODE REVIEW

**Comment by chrisharm** [comment]
I just released 1.31 of commons-jaxrs.  Give it a few hours and it should be available in maven central.

**Comment by bdemers** [comment]
I'll rebase this one after #4 goes in

**Comment by bdemers** [comment]
I thought i had already rebased this... 🤔

**Comment by bdemers** [comment]
Ha, I had only updated the commons-jaxrs dep version, not the GAV.
Fixed :)

**Pull request merged**
