### PR TITLE
Remove split paackage in scim-spec-schema and scim-spec-protocol

### PR DESCRIPTION
**Pull request by bdemers**
- Move all protocol classes under common package
- Merge scim-spec-schema and scim-spec-protocol into scim-spec

### CODE REVIEW

**Review by smoyer64 — COMMENTED** [review]
@bdemers - What's the rationale for combining these packages ... not opposed but the (original rationale for separating them was to have a package per RFC.  I'm also assuming that code related to RFC7642 would also go into the combined package?

**Comment by bdemers** [comment]
Hey @smoyer64 

I started a thread on the SCIMple list asking about this:
https://lists.apache.org/thread/ds744czqo4j5j5vrot64o0309v0ffmyf

My thinking behind merging them is, if typical usage of SCIMple (a client or server), is going to require both modules, merging them keeps things simple (less confusion for developers downstream, easier to refactor code within a package, etc)

One minor downside of merging them is using the schema-related classes, which means there is an added dependency on `swagger-annotations`, but that doesn't have any [transitive dependencies](https://search.maven.org/artifact/io.swagger.core.v3/swagger-annotations/2.2.2/jar), so doesn't add much bloat. (And if typical usage requires both schema and protocol, that issues is moot anyway)


That said, there are a few open questions from my original thread:
* Is consumption of the server and client modules the most common usage of SCIMple. (I'm assuming this is the case, but would like to confirm)
* A few classes in the protocol module needed to be moved to another (Java) package.  Naming is hard, so I'm not sure this PR organizes them the best. My original thread suggested:
  - `org.apache.directory.scim.spec.core`
  - `org.apache.directory.scim.spec.protocol`

  Where this PR only moved the `protocol` classes.
  

As for RFC7642, I don't think any code is directly needed for that RFC, as it's mostly background and use-cases.  Though that probably would be good bases for integration tests (or a future compliance suite).


Thoughts and ideas welcome!!

**Review by smoyer64 — APPROVED** [review]
It makes sense to me ... I was imagining that there might be some "helper" code that made it into the library as part of RFC7642 but you're right that there isn't any at the moment.  I haven't followed it closely but there was also talk of a spec for SCIM security.

Either way, having one JAR for all specs seems like a great simplification!

**Comment by bdemers** [comment]
Rethinking merging these modules a bit, the `schema` module had JAX-RS-related dependencies, it doesn't actually need them.
Keeping the modules separate helps keep web bits from leaking into schema-related classes.

**Comment by smoyer64** [comment]
If you're only processing SCIM resources, you don't need any of the "web bits" so perhaps there's a use-case for keeping them separate.  I'm ambivalent as I'm using Go (and the PennState client) for SCIM at the moment so I'll leave it to your discretion.  I will however mark the PR as draft so that someone doesn't merge it before you've decided.

**Comment by bdemers** [comment]
split package issue has been resolved durring other refactoring

**Pull request closed without merging**
