### PR TITLE
Added place holder logo image in README

### PR DESCRIPTION
**Pull request by bdemers**
More testing of CI...

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by smoyer64** [comment]
I'm not sure why this is in conflict except the top-level heading is __Apache Directory SCIMple__ on the develop branch.  I also noticed that this link in this file points to the Fortress API documentation.  I'll merge this if it's still a valid PR.

**Comment by bdemers** [comment]
Fixed (painfully using the GH editor)

Is there a better project logo to use?

**Comment by smoyer64** [comment]
Not that I know of ... that should at least do for now.  Thanks!

**Pull request merged**
