### PR TITLE
Updating NOTICE file based on Apache ref doc

### PR DESCRIPTION
**Pull request by bdemers**
https://www.apache.org/dev/licensing-howto.html

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by bdemers** [comment]
(mostly pushing this to see if the CI trigger will work)

**Comment by bdemers** [comment]
build not triggering...

**Comment by smoyer64** [comment]
@ussmith This is marked WIP
@bdemers Should we revert?

**Comment by bdemers** [comment]
No the change is fine, I only marked it `WIP` cause I was trying to figure out why the CI builds are not triggering.  Typically the easiest way to validate they are working is by creating simple PRs like this. I've reached out to the `builds` list for more support on this.

**Pull request merged**
