### PR TITLE
SCIMPLE-87 - Update dependencies

### PR DESCRIPTION
**Pull request by ccrvincent**
Update dependencies with CVEs or that block building on a Java 11 JDK.

### CODE REVIEW

**Comment by smoyer64** [comment]
Thanks for the update ... I'm working on SCIMple for the next couple weeks and expect to take care of a bunch of the issues in Jira.  We just found another problem with eTag generation the other day so stay tuned.

**Comment by ccrvincent** [comment]
We're building out support to go beyond Okta, so expect to see more filings and fixes.  I'm just getting ready to add `scim-server-common` to the project to handle the `attributes` and `excludedAttributes` parameters.

**Comment by smoyer64** [comment]
I'm working on creating diffs so that I can patch the PennState SCIMple changes into the Apache project.  Once we get our internal projects on this library, we'll only modify the code here.

We're using ``attributes`` and ``externalAttributes`` ... I guess there's more work to do than I realized!

**Comment by ccrvincent** [comment]
If you're using them, I have high hopes for a short QA cycle from adding them into our implementation!

**Pull request merged**
